### ISSUE TITLE
minor issue at first start

### ISSUE THREAD

**Issue by TaigaSan** [d4rkcat/pia#3]
hi, i'm new to github...maybe it's not the right way to submit.
thanks for your pia.sh.

at first start, after entering user/passwd : 
"cat: /etc/openvpn/pia/servers.txt: No such file or directory"
and when selecting a server
"[X] 27 is not valid! 1-0 only."
works well if we start again.

original : 
MAXSERVERS=$(cat $VPNPATH/servers.txt | wc -l)
.
.
if [ ! -f $VPNPATH/servers.txt ];then fupdate;fi

proposal : 
if [ ! -f $VPNPATH/servers.txt ];then fupdate;fi                         //first
MAXSERVERS=$(cat $VPNPATH/servers.txt | wc -l)              //next

**Comment by d4rkcat** [comment]
Thanks @TaigaSan,
Fixed!
