### ISSUE TITLE
Killswitch

### ISSUE THREAD

**Issue by RafalHo** [d4rkcat/pia#6]
Hi, would there be a chance for local access to work after activating killswitch?
I use your mega script on RaspberryPi, to which I connect using VNC. After activating the killswitch and terminating the script, I need to physically connect the monitor and keyboard to run the script again.

Thank you in advance for your reply and I apologize for my bad English.
Rafal

**Comment by d4rkcat** [comment]
Hi @RafalHo ,
Unfortunately the killswitch is designed to kill all network connectivity in the event of loss of VPN connection. To add an exception would be to break the killswitch.
Have you considered using the firewall (-f) instead? It doesn't allow any traffic apart from tunnel, so it also works as a killswitch.
Cheers
