### ISSUE TITLE
Run on TomatoUSB

### ISSUE THREAD

**Issue by thyeestes** [d4rkcat/pia#8]
Hi I want to try your script on my TomatoUSB router, but I get different kind of errors, like 
pia: line 550: tput: command not found
pia: line 582: id: command not found
pia: line 582: [: !=: unary operator expected
 Is it not possible to run it on TomatoUSB router? What I try to accomplish is to get a forwarded port for Transmission which runs on my NAS.

**Comment by d4rkcat** [comment]
Hi, sorry this script is meant for endpoints, not routers.
There are many things that will not work if you try to run it on a router.
